# docker-compose.yml
version: '3'
services:
  postgres:
    container_name: colyseus-postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nakama"]
      interval: 3s
      timeout: 3s
      retries: 5
  nakama:
    build: ./nakama
    container_name: colyseus-nakama
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres:localdb@postgres:5432/nakama        
    restart: always
    links:
      - "postgres:db"
    # restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  # redis:
  #   image: redis:7
  #   container_name: colyseus-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - coly-net

  # colyseus:
  #   build: .
  #   container_name: colyseus
  #   restart: unless-stopped
  #   environment:
  #     - PORT=2567
  #     - REDIS_URL=redis://redis:6379
  #     - NODE_ENV=development
  #     - NAKAMA_URL=localhost:7350
  #   depends_on:
  #     - redis
  #     - nakama
  #   ports:
  #     - "2567:2567"
  #   networks:
  #     - coly-net

volumes:
  postgres-data:
  redis-data:

networks:
  coly-net:
    driver: bridge
